# Generated by Django 4.1.12 on 2023-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryofcompany',
            name='category',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='companystatus',
            name='status',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcategoryofcompany',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatus',
            name='status',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsector',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsharetype',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sharetype',
            name='type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
