# Generated by Django 4.1.12 on 2024-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsector',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
