# Generated by Django 4.1.12 on 2024-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0002_historicalsector_short_name_sector_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('percent', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Percent',
                'db_table': 'percent',
            },
        ),
    ]
