# Generated by Django 4.1.12 on 2024-05-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0003_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percent',
            name='percent',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
