# Generated by Django 4.1.12 on 2023-12-12 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'category_of_company',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=256)),
                ('comment', models.TextField(blank=True, max_length=1024)),
                ('link', models.CharField(blank=True, max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.categoryofcompany')),
            ],
            options={
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Company statuses',
                'db_table': 'company_status',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=128)),
                ('comment', models.TextField(blank=True, max_length=1024)),
                ('website', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'contact_type',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'sector',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, max_length=1024)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.company')),
            ],
            options={
                'db_table': 'share',
            },
        ),
        migrations.CreateModel(
            name='ShareType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'share_type',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='SharePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('date', models.DateField()),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.share')),
            ],
            options={
                'db_table': 'share_price',
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('complite', models.BooleanField(default=True)),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_edit_datetime', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, max_length=1024)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shareholder_add', to=settings.AUTH_USER_MODEL)),
                ('last_edit_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shareholder_edit', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.contact')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.share')),
            ],
            options={
                'db_table': 'shareholder',
            },
        ),
        migrations.AddField(
            model_name='share',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.sharetype'),
        ),
        migrations.CreateModel(
            name='SeedStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_term', models.DateField()),
                ('end_term', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.company')),
            ],
            options={
                'db_table': 'seed_step',
                'ordering': ['-end_term'],
            },
        ),
        migrations.CreateModel(
            name='OurTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(verbose_name='Amount of Shares')),
                ('price', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Price per 1 share')),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_edit_datetime', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, max_length=1024)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='our_transaction_add', to=settings.AUTH_USER_MODEL)),
                ('last_edit_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='our_transaction_edit', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.share')),
            ],
            options={
                'db_table': 'our_transaction',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'location',
                'unique_together': {('city', 'country')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.contacttype'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.companystatus'),
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('company', 'type')},
        ),
    ]
