# Generated by Django 4.1.12 on 2023-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='historicalourtransaction',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='historicalourtransaction',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Cost per share'),
        ),
        migrations.AlterField(
            model_name='historicalshare',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='historicalshareholder',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='historicalshareprice',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Cost per share'),
        ),
        migrations.AlterField(
            model_name='ourtransaction',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='ourtransaction',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Cost per share'),
        ),
        migrations.AlterField(
            model_name='share',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='comment',
            field=models.TextField(blank=True, max_length=10240),
        ),
        migrations.AlterField(
            model_name='shareprice',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Cost per share'),
        ),
    ]
