# Generated by Django 4.1.12 on 2023-12-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='category_id',
            new_name='category',
        ),
    ]
