# Generated by Django 4.1.12 on 2023-12-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_company_table_alter_location_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurTransactions',
            new_name='OurTransaction',
        ),
    ]
