# Generated by Django 4.1.12 on 2024-01-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_company_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoneytransaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Cost'),
        ),
        migrations.CreateModel(
            name='FairValueMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('percent', models.IntegerField()),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.company')),
            ],
            options={
                'verbose_name_plural': '',
                'db_table': 'fair_value_method',
            },
        ),
    ]
