# Generated by Django 4.1.12 on 2023-12-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_ourtransactions_ourtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city']},
        ),
        migrations.AlterModelOptions(
            name='ourtransaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ourtransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
