# Generated by Django 4.1.12 on 2024-01-12 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_historicalmoneytransaction_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': '02. Companys'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '01. Contacts'},
        ),
        migrations.AlterModelOptions(
            name='fairvaluemethod',
            options={'verbose_name_plural': '10. Fair Value Method'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompany',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical company', 'verbose_name_plural': 'historical 02. Companys'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontact',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact', 'verbose_name_plural': 'historical 01. Contacts'},
        ),
        migrations.AlterModelOptions(
            name='historicalmoneytransaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical money transaction', 'verbose_name_plural': 'historical 04. Money Transactions'},
        ),
        migrations.AlterModelOptions(
            name='historicalseedstep',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical seed step', 'verbose_name_plural': 'historical 09. Seed Steps'},
        ),
        migrations.AlterModelOptions(
            name='historicalshare',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical share', 'verbose_name_plural': 'historical 03. Shares'},
        ),
        migrations.AlterModelOptions(
            name='historicalshareholder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical shareholder', 'verbose_name_plural': 'historical 07. Shareholders'},
        ),
        migrations.AlterModelOptions(
            name='historicalshareprice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical share price', 'verbose_name_plural': 'historical 06. Share Price'},
        ),
        migrations.AlterModelOptions(
            name='historicalsharetransaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical share transaction', 'verbose_name_plural': 'historical 05. Share Transaction'},
        ),
        migrations.AlterModelOptions(
            name='moneytransaction',
            options={'ordering': ['-date'], 'verbose_name_plural': '04. Money Transactions'},
        ),
        migrations.AlterModelOptions(
            name='seedstep',
            options={'ordering': ['-end_term'], 'verbose_name_plural': '09. Seed Steps'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'verbose_name_plural': '03. Shares'},
        ),
        migrations.AlterModelOptions(
            name='shareholder',
            options={'verbose_name_plural': '07. Shareholders'},
        ),
        migrations.AlterModelOptions(
            name='shareprice',
            options={'verbose_name_plural': '06. Share Price'},
        ),
        migrations.AlterModelOptions(
            name='sharetransaction',
            options={'verbose_name_plural': '05. Share Transaction'},
        ),
        migrations.AlterModelOptions(
            name='split',
            options={'verbose_name_plural': '08. Splits'},
        ),
        migrations.CreateModel(
            name='HistoricalFairValueMethod',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('percent', models.IntegerField()),
                ('date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fair value method',
                'verbose_name_plural': 'historical 10. Fair Value Method',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
