# Generated by Django 4.1.12 on 2024-01-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_company_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='share',
        ),
        migrations.DeleteModel(
            name='HistoricalShareholder',
        ),
        migrations.DeleteModel(
            name='Shareholder',
        ),
    ]
