# Generated by Django 4.1.12 on 2024-01-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_fairvaluemethod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='shareholder_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shareholderlist'),
        ),
    ]
