# Generated by Django 4.1.12 on 2024-02-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_shareholder_shareholder_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='link',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='link',
        ),
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
