# Generated by Django 4.1.12 on 2024-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_company_number_alter_historicalcompany_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='number',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
