# Generated by Django 4.1.12 on 2024-02-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_companyhouseparser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhouseparser',
            name='shareholder_list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.share', unique=True),
        ),
    ]
