# Generated by Django 4.1.12 on 2024-02-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_companyhouseparser_shareholder_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhouseparser',
            name='shareholder_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.share'),
        ),
    ]
