# Generated by Django 4.1.12 on 2024-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_companyhouseparser_shareholder_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhouseparser',
            name='file_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
