# Generated by Django 4.1.12 on 2024-02-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_companyhouseparser_file_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyHouseParser',
        ),
    ]
