# Generated by Django 4.1.12 on 2024-02-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_companyhouseparser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHouseParser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=32)),
                ('parsing_datetime', models.DateTimeField(auto_now_add=True)),
                ('file_date', models.DateField()),
                ('comment', models.TextField(blank=True, max_length=10240)),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.company')),
                ('shareholder_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.share')),
            ],
            options={
                'verbose_name_plural': '12. Company House Parser',
                'db_table': 'company_house_parser',
                'unique_together': {('company_id', 'transaction_id')},
            },
        ),
    ]
