# Generated by Django 4.1.12 on 2024-02-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_companyhouseparser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyhouseparser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='companyhouseparser',
            name='shareholder_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.shareholderlist'),
        ),
    ]
