# Generated by Django 4.1.12 on 2024-02-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_alter_companyhouseparser_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompanyHouseParser',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('transaction_id', models.CharField(max_length=32)),
                ('parsing_datetime', models.DateTimeField(blank=True, editable=False)),
                ('file_date', models.DateField()),
                ('comment', models.TextField(blank=True, max_length=10240)),
                ('status', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shareholder_list', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.shareholderlist')),
            ],
            options={
                'verbose_name': 'historical company house parser',
                'verbose_name_plural': 'historical 12. Company House Parser',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
