# Generated by Django 4.1.12 on 2024-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_companyhouseparser_shareholder_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairvaluemethod',
            name='color',
            field=models.CharField(choices=[('#92d14f', 'Green'), ('#ffff00', 'Yellow'), ('#fe0000', 'Red')], default='#ffffff', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalfairvaluemethod',
            name='color',
            field=models.CharField(choices=[('#92d14f', 'Green'), ('#ffff00', 'Yellow'), ('#fe0000', 'Red')], default='#ffffff', max_length=8),
        ),
    ]
