# Generated by Django 4.1.12 on 2024-03-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_fairvaluemethod_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfairvaluemethod',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalfairvaluemethod',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='FairValueMethod',
        ),
        migrations.DeleteModel(
            name='HistoricalFairValueMethod',
        ),
    ]
