# Generated by Django 4.1.12 on 2024-03-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0003_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_remove_historicalfairvaluemethod_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairValueList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, max_length=10240)),
            ],
            options={
                'verbose_name_plural': '11. Fair Value List',
                'db_table': 'fair_value_list',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFairValueMethod',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('comment', models.TextField(blank=True, max_length=10240)),
                ('color', models.CharField(blank=True, choices=[('#92d14f', 'Green'), ('#ffff00', 'Yellow'), ('#fe0000', 'Red')], max_length=8, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.company')),
                ('fair_value_list', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.fairvaluelist')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('percent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base_info.percent')),
            ],
            options={
                'verbose_name': 'historical fair value method',
                'verbose_name_plural': 'historical 11. Fair Value Method',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFairValueList',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, max_length=10240)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fair value list',
                'verbose_name_plural': 'historical 11. Fair Value List',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FairValueMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, max_length=10240)),
                ('color', models.CharField(blank=True, choices=[('#92d14f', 'Green'), ('#ffff00', 'Yellow'), ('#fe0000', 'Red')], max_length=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.company')),
                ('fair_value_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.fairvaluelist')),
                ('percent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_info.percent')),
            ],
            options={
                'verbose_name_plural': '11. Fair Value Method',
                'db_table': 'fair_value_method',
            },
        ),
    ]
