# Generated by Django 4.1.12 on 2024-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_fairvaluemethod_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyhouseparser',
            options={'verbose_name_plural': '13. Company House Parser'},
        ),
        migrations.AlterModelOptions(
            name='fairvaluemethod',
            options={'verbose_name_plural': '12. Fair Value Method'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompanyhouseparser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical company house parser', 'verbose_name_plural': 'historical 13. Company House Parser'},
        ),
        migrations.AlterModelOptions(
            name='historicalfairvaluemethod',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical fair value method', 'verbose_name_plural': 'historical 12. Fair Value Method'},
        ),
        migrations.AlterField(
            model_name='fairvaluemethod',
            name='color',
            field=models.CharField(blank=True, choices=[('', '---------'), ('#92d14f', 'Green'), ('#ffff00', 'Yellow'), ('#fe0000', 'Red')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfairvaluemethod',
            name='color',
            field=models.CharField(blank=True, choices=[('', '---------'), ('#92d14f', 'Green'), ('#ffff00', 'Yellow'), ('#fe0000', 'Red')], max_length=8, null=True),
        ),
    ]
